---
title: "Speed_analysis"
author: "E. Alejandro Pardo"
date: "2025-07-10"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pracma)
library(rstatix)
library(gridExtra)
library(readxl)
library(ggh4x)
library(ggforce)
library(patchwork) 
library(signal)
library(dplyr)
library(writexl)
library(RHRV)
library(dplyr)
library(writexl)
library(fuzzyjoin)
library(readxl)
library(stringr)
library(purrr)

setwd("C:/Users/jandr/OneDrive - Universidad del rosario/Heart_rate_speed_HRV/Datos/Videos freq. cardiaca/Results_optocardiography")

ids_disponibles <- c(19,20,21,22,25,26,30,32)
heart_speed_results <- list()  # Create an empty list to store results
dir.create("Graphs_speed", showWarnings = FALSE)
for (id in ids_disponibles) {
  filename <- paste0("Movimiento_", id, "_curva_contraccion.csv")
  
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean(ovalo")) %>%
    mutate(t = seq(0, 20, length.out = n())) %>%
    pivot_longer(-t, names_to = "ovalo", values_to = "value") %>%
    mutate(
      num_ovalo = as.numeric(str_extract(ovalo, "\\d+")),
      t = t + (num_ovalo - 1) * 20 
    )  

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.99 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 18
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")

  breaks <- seq(0, 80, by = 20)
  data_smoothed$interval_20s <- cut(
    data_smoothed$t,
    breaks = breaks,
    right = TRUE,
    include.lowest = TRUE
  )

  final_valleys$interval_20s <- cut(
    final_valleys$time,
    breaks = breaks,
    right = TRUE,
    include.lowest = TRUE
  )

  final_peaks$interval_20s <- cut(
    final_peaks$time,
    breaks = breaks,
    right = TRUE,
    include.lowest = TRUE
  )

  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    facet_wrap(~interval_20s, scales = "free_x") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = paste0("Graphs_speed/moving", id, ".png"),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  heart_speed_results[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
}

data_suavizado_speed <- map_dfr(heart_speed_results, "data_suavizado")
valles_speed_mov <- map_dfr(heart_speed_results, "valles_finales")
picos_speed_mov <- map_dfr(heart_speed_results, "picos_finales")

# Merge all results
View(valles_speed_mov)
```




```{r}

folder_path_speed <- "C:/Users/jandr/OneDrive - Universidad del rosario/Heart_rate_speed_HRV/Datos/Videos freq. cardiaca/Results_speed"
list.files()
# Leer el archivo CSV (ajusta el nombre si es necesario)

files <-  list.files(path = folder_path_speed, pattern = "*spots*", full.names = TRUE)
print(files)
read_and_label <- function(file) {
  df <- read.csv(file)
  df <- df[-c(1:3), ]
  df <- df[, 1:9]
  df$ID <- as.numeric(df$ID)
  df$TRACK_ID <- as.numeric(df$TRACK_ID)
  df$QUALITY <- as.numeric(df$QUALITY)
  df$POSITION_X <- as.numeric(df$POSITION_X)
  df$POSITION_Y <- as.numeric(df$POSITION_Y)
  df$POSITION_Z <- as.numeric(df$POSITION_Z)
  df$POSITION_T <- as.numeric(df$POSITION_T)
  df$FRAME <- as.numeric(df$FRAME)
  df$source_file <- basename(file)  # Add filename column
  return(df)
  
  return(df)
}

data_list <- lapply(files, read_and_label)
merged_data_rapidez <- bind_rows(data_list)


##############################################################################################
Data_rap <- merged_data_rapidez
  print(Data_rap)

Data_rap <- Data_rap %>%
  mutate(Section = as.numeric(str_extract(source_file, "(?<=Speed_)\\d+")), Snail = as.numeric(str_extract(source_file, "(?<=Mov_)\\d+")))

View(Data_rap)

rangos <- Data_rap %>%
  group_by(Snail, Section, TRACK_ID) %>%
  summarise(
    start_frame = min(FRAME, na.rm = TRUE),
    end_frame = max(FRAME, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Snail, Section, start_frame)

rangos_filtrados <- rangos %>%
  inner_join(rangos, by = c("Snail", "Section"), suffix = c("_a", "_b")) 

  # Filtramos: ID_a está contenido dentro de ID_b (pero son diferentes)
rangos_filtrados <- rangos_filtrados %>%   dplyr::filter(
    TRACK_ID_a != TRACK_ID_b,
    start_frame_a >= start_frame_b,
    end_frame_a <= end_frame_b
  ) %>%
   distinct(Snail, Section, TRACK_ID_eliminar = TRACK_ID_a)

# Eliminamos esos TRACK_IDs del dataframe original
rangos_no_contenidos <- rangos %>%
  anti_join(rangos_filtrados, by = c("Snail", "Section", "TRACK_ID" = "TRACK_ID_eliminar"))

rangos_ajustados <- rangos_no_contenidos %>%
  group_by(Snail, Section) %>%
  arrange(start_frame) %>%
  mutate(
    end_frame_anterior = lag(end_frame, default = -Inf),
    start_frame_ajustado = pmax(start_frame, end_frame_anterior + 1)
  ) %>%
  dplyr::filter(start_frame_ajustado <= end_frame) %>%
  select(Snail, Section, TRACK_ID, start_frame = start_frame_ajustado, end_frame) %>%
  ungroup()


datos_filtrados <- Data_rap %>%
  inner_join(rangos_ajustados, by = c("Snail", "Section", "TRACK_ID")) %>%
  dplyr::filter(FRAME >= start_frame & FRAME <= end_frame)

datos_filtrados <- datos_filtrados %>%
  arrange(Snail, Section, TRACK_ID, FRAME) %>%
  group_by(Snail, Section, TRACK_ID) %>%
  mutate(
    distancia = (POSITION_X - lag(POSITION_X)), ###distancia = sqrt((POSITION_X - lag(POSITION_X))^2),
    velocidad = distancia / 0.0333, 
  distancia = replace_na(distancia, 0)
  ) %>%
  ungroup()

datos_filtrados <- datos_filtrados %>%
  mutate(
    time = (FRAME * 0.0333) + ( (Section - 1) * 20 )
  )

View(datos_filtrados)
write_xlsx(datos_filtrados, "data_speed_distance.xlsx")

############################################################################################3333
resumen_por_caracol_y_sección <- datos_filtrados %>%
  group_by(Snail, Section) %>%
  summarise(
    desplazamiento_total_mm = sum(distancia, na.rm = TRUE),
    velocidad_promedio_mm_s = mean(velocidad, na.rm = TRUE),
    frames_observados = n(),
    .groups = "drop"
  )


resumen_por_caracol <- datos_filtrados %>%
  group_by(Snail) %>%
  summarise(
    desplazamiento_total_mm = sum(distancia, na.rm = TRUE),
    velocidad_promedio_mm_s = mean(velocidad, na.rm = TRUE),
    frames_observados = n(),
    .groups = "drop"
  )


# Asegúrate que ambos tienen la columna time
frecuencia_instantanea <- valles_speed_mov %>% 
  arrange(ID, time) %>%
  group_by(ID) %>%
  mutate(
    intervalo = time - lag(time),
    frecuencia_inst = 60 / intervalo
  ) %>%
  ungroup()
view(frecuencia_instantanea)
frecuencia_instantanea <- frecuencia_instantanea %>% rename( "Snail" =ID)


# Redondear el tiempo hacia abajo al múltiplo de 5 más cercano
heart_rate_5s <- frecuencia_instantanea %>%
  mutate(time_5s = (floor(time / 5) * 5)+5) %>%
  group_by(Snail, time_5s) %>%
  summarise(heart_rate_5s = mean(frecuencia_inst, na.rm = TRUE), .groups = "drop") %>% dplyr::filter(Snail %in% c(19, 20, 21, 22, 25, 26, 30, 32))
view(heart_rate_5s)

speed_5s <- datos_filtrados %>%
  mutate(time_5s = (floor(time / 5) * 5)+5) %>%
  group_by(Snail, time_5s) %>%
  summarise(speed_5s = mean(velocidad, na.rm = TRUE), .groups = "drop")


distance_5s <- datos_filtrados %>%
  mutate(time_5s = (floor(time / 5) * 5)+5) %>%
  group_by(Snail, time_5s) %>%
  summarise(distance_5s = mean(distancia, na.rm = TRUE), .groups = "drop")

Inst_speed <- inner_join(speed_5s, heart_rate_5s, by = c("Snail", "time_5s")) %>%
  inner_join(distance_5s, by = c("Snail", "time_5s"))

Inst_speed$speed_cm_min <- Inst_speed$speed_5s * 6


write_xlsx(Inst_speed, "Inst_speed_.xlsx")
view(Inst_speed)

###################################################################################################
setwd("C:/Users/jandr/OneDrive - Universidad del rosario/Heart_rate_speed_HRV/Datos")
list.files()
Inst_speed <- read_xlsx("Pardo-Sarmiento et al, cornu aspersum.xlsx", sheet = "5s_speed_heart_Rate")
library(ggplot2)
library(lme4)
library(scales)  # para pretty_breaks()
view(Inst_speed)
snail_colors <- nail_colors <- c(
  "19" = "#1b9e77",
  "20" = "#d95f02",
  "21" = "#7570b3",
  "22" = "darkblue",
  "25" = "#e7298a",
  "26" = "#66a61e",
  "30" = "#e6ab02",
  "32" = "black"
  # Add more if you have more Snail IDs
)

ggplot(data = Inst_speed, aes(x = speed_cm_min, y = heart_rate_5s, fill = as.factor(Snail))) +
  geom_smooth(aes(color = as.factor(Snail)),size = 1.5, method = "lm", formula = y ~ x, se = TRUE, alpha = 0.1) +
  geom_point(aes(fill = as.factor(Snail)), size = 1.5, shape = 21, stroke = 0.3, alpha = 0.3) +
  scale_fill_manual(values = snail_colors, name = "Snail") +
    scale_color_manual(values = snail_colors, name = "Snail") +
  scale_x_continuous(expand = expansion(mult = c(0, 0)), breaks = pretty_breaks(n = 8)) +
  scale_y_continuous(breaks = pretty_breaks(n = 6)) +
  theme_bw(base_size = 14) +
  theme(
    axis.line = element_line(color = "black", size = 0.8),
    axis.line.x.bottom = element_line(color = "black", size = 0.8),
    axis.line.y.left = element_line(color = "black", size = 0.8),
    panel.grid.major = element_line(color = "black", linetype = "dotted", size = 0.3), 
  )




ggplot(data = Inst_speed, aes(x = speed_cm_min, y = heart_rate_5s)) +
  geom_smooth(color = "#FF7256",size = 2, method = "lm", formula = y ~ x, se = TRUE, alpha = 0.1) +
  geom_point(fill= "#FF7256", size = 2, shape = 21, stroke = 0.3, alpha = 0.3) +
    scale_fill_manual(values = snail_colors, name = "Snail") +
  scale_x_continuous(expand = expansion(mult = c(0, 0)), breaks = pretty_breaks(n = 8)) +
  scale_y_continuous(breaks = pretty_breaks(n = 6)) +
  theme_bw(base_size = 14) +
  theme(
    axis.line = element_line(color = "black", size = 0.8),
    axis.line.x.bottom = element_line(color = "black", size = 0.8),
    axis.line.y.left = element_line(color = "black", size = 0.8),
    panel.grid.major = element_line(color = "black", linetype = "dotted", size = 0.3), 
  )

library(lme4)
library(MuMIn)

modelo_mixto <- lmer(heart_rate_5s ~ (speed_cm_min) * (1 | Snail), data = Inst_speed)
summary(modelo_mixto)

modelo1 <- lmer(heart_rate_5s ~ speed_cm_min + `Total_mass(g)`  + (1|Snail), data = Inst_speed)
summary(modelo1)

r.squaredGLMM(modelo1)

###########################################################################################


```
